'use client';
import { actionIssue, actionSteps, browserCapable, SHORTCUT_KEYS, shortcutFor, triggerLabel, type DeckAction, type ActionSettings, type ActionStep } from './deck-actions';
import './deck-actions.css';

export default function ActionEditor<T extends DeckAction>({ value, index, onChange, onTest }: { value:T; index:number; onChange:(value:T)=>void; onTest:()=>void }) {
  const s = value.settings ?? {}, issue = actionIssue(value);
  const patch = (settings:Partial<ActionSettings>) => onChange({...value, settings:{...s,...settings}});
  const steps = s.steps ?? [];
  const updateStep = (i:number, step:ActionStep) => patch({steps:steps.map((old,j)=>i===j?step:old)});
  const moveStep = (i:number, direction:number) => { const next=[...steps]; [next[i],next[i+direction]]=[next[i+direction],next[i]]; patch({steps:next}); };
  return <section className="action-details" aria-label="액션 세부 설정">
    {value.kind==='keyboard' && <><label htmlFor="shortcut">Windows 단축키</label><input id="shortcut" value={shortcutFor(value)} onChange={e=>patch({shortcut:e.target.value})} placeholder="Ctrl+Shift+S" list="shortcut-examples"/><datalist id="shortcut-examples">{['Ctrl+C','Ctrl+V','Ctrl+Z','Ctrl+S','Ctrl+Shift+S','Win+Shift+S','Win+D','Win+V',...SHORTCUT_KEYS].map(v=><option key={v} value={v}/>)}</datalist><p>Ctrl / Alt / Shift / Win 조합과 영문 키 이름을 사용하세요. 기기에 기록하면 사이트 없이 동작합니다. 기존 ⌘ 단축키는 Windows용 Ctrl 조합으로 해석합니다.</p></>}
    {(value.kind==='website'||(value.kind==='system'&&value.action==='Open website')) && <><label htmlFor="target-url">열 웹페이지 주소</label><input id="target-url" type="url" value={s.url??''} onChange={e=>patch({url:e.target.value})} placeholder="https://example.com/project"/><p>사이트 실행 모드에서는 새 탭으로 엽니다. 다른 앱을 사용하는 중에는 Windows 실행 파일을 이용하세요.</p></>}
    {value.kind==='application' && <><label htmlFor="app-path">Windows 실행 파일 경로 (.exe)</label><input id="app-path" value={s.appPath??''} onChange={e=>patch({appPath:e.target.value})} placeholder={'C:\\Program Files\\Adobe\\Adobe Photoshop 2026\\Photoshop.exe'}/><p>Windows 탐색기에서 실제 .exe 파일을 우클릭 → 「경로로 복사」하여 붙여넣으세요. 예시는 자동 지정되지 않습니다. 브라우저에서는 설치된 앱을 검색하거나 직접 실행할 수 없습니다.</p><p><b>저장 → 기기 적용 → Windows 실행 파일 받기</b> 순서로 연결합니다. AutoHotkey v2가 실행을 담당합니다.</p></>}
    {(value.kind==='ai'||value.kind==='agent') && <><label htmlFor="ai-target">사용할 AI 서비스</label><select id="ai-target" value={['https://chatgpt.com/','https://claude.ai/','https://gemini.google.com/'].includes(s.url??'https://chatgpt.com/') ? s.url??'https://chatgpt.com/' : 'custom'} onChange={e=>patch({url:e.target.value==='custom'?'':e.target.value})}><option value="https://chatgpt.com/">ChatGPT</option><option value="https://claude.ai/">Claude</option><option value="https://gemini.google.com/">Gemini</option><option value="custom">직접 지정</option></select><label htmlFor="ai-url">AI 페이지 주소</label><input id="ai-url" type="url" value={s.url??'https://chatgpt.com/'} onChange={e=>patch({url:e.target.value})}/><p>지시문을 복사한 뒤 AI 페이지를 엽니다. 그곳에서 붙여넣고 직접 전송하세요. API 키·유료 API 호출 없이 사용하며, 자동 질문·응답 수집은 하지 않습니다.</p></>}
    {value.kind==='system'&&value.action==='Copy text' && <><label htmlFor="copy-text">복사할 텍스트</label><textarea id="copy-text" value={s.text??''} maxLength={8000} onChange={e=>patch({text:e.target.value})}/></>}
    {value.kind==='macro' && <><h3>실행 단계</h3><p>사이트에서는 한 단계씩 실행합니다. Windows 실행 파일은 아래 순서대로 자동 실행하며 텍스트를 현재 앱에 입력합니다.</p>{steps.map((step,i)=><div className="action-step-editor" key={i}><label htmlFor={`step-kind-${i}`}>단계 {i+1}</label><select id={`step-kind-${i}`} value={step.kind} onChange={e=>updateStep(i,{kind:e.target.value as ActionStep['kind'],value:''})}><option value="text">텍스트 입력 / 사이트에서는 복사</option><option value="url">웹페이지 열기</option><option value="wait">대기 (ms)</option></select><textarea aria-label={`단계 ${i+1} 값`} value={step.value} onChange={e=>updateStep(i,{...step,value:e.target.value})} placeholder={step.kind==='url'?'https://…':step.kind==='wait'?'500':'입력할 텍스트'}/><div><button disabled={i===0} onClick={()=>moveStep(i,-1)} aria-label={`단계 ${i+1} 위로`}>↑</button><button disabled={i===steps.length-1} onClick={()=>moveStep(i,1)} aria-label={`단계 ${i+1} 아래로`}>↓</button><button onClick={()=>patch({steps:steps.filter((_,j)=>i!==j)})}>삭제</button></div></div>)}<button className="secondary-wide" disabled={steps.length>=16} onClick={()=>patch({steps:[...steps,{kind:'text',value:''}]})}>＋ 단계 추가</button></>}
    <div className={`action-readiness ${issue?'incomplete':''}`} role="status"><b>{issue?'설정 필요':shortcutFor(value)?'기기에 직접 기록':value.kind==='application'?'Windows 연동 준비됨':'사이트에서 실행 가능'}</b><p>{issue??(shortcutFor(value)?shortcutFor(value):`기기 입력 ${triggerLabel(index)} · ${value.kind==='application'?'실제 파일 존재 여부는 Windows에서 확인됩니다.':`${actionSteps(value).length}단계 · 사이트 실행 모드 또는 Windows 실행 파일 사용`}`)}</p></div>
    <button className="secondary-wide" onClick={onTest} disabled={!browserCapable(value)}>저장 전 사이트에서 실행 테스트</button>
  </section>;
}
